### ISSUE TITLE
Add slate peerDependency?

### ISSUE THREAD

**Issue by golmansax** [tommoor/slate-md-serializer#13]
First off, thanks for creating this package.  It took a while to find it but has been great so far.

I had to lock down my Slate dependency to `^0.32.4` (`^0.34` didn't work).  What do you think about adding that to the peer dependencies?

**Comment by tommoor** [comment]
Yea, that seems like a good idea the peer dependency is too wide right now as Slate makes breaking changes on minor releases

**Comment by tommoor** [comment]
closed by 7db1eba0c5463787e1335b14b46c52a7446d9254

**Comment by golmansax** [comment]
@tommoor Thanks for adding this
