### ISSUE TITLE
inCodeBlock doesn't actually check for it

### ISSUE THREAD

**Issue by Lukavyi** [tommoor/slate-md-serializer#16]
```javascript
const inCodeBlock = !!document.getClosest(node.key, n => {
  n.type === "code";
});
```

The arrow function doesn't return anything, but it should

https://github.com/tommoor/slate-md-serializer/blob/master/src/renderer.js#L201

**Comment by tommoor** [comment]
Hmm, it does look like you're right although this hasn't caused a problem in practice. Clearly the test needs some work here too.

**Comment by Lukavyi** [comment]
Seems that it would always equal to false, thus making the `inCodeBlock`redundant
