### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by markolofsen** [tommoor/slate-md-serializer#25]
Can you upload online example?

**Comment by tommoor** [comment]
Hi, the best example of the serializer in use is in `rich-markdown-editor`, deserialize:

https://github.com/outline/rich-markdown-editor/blob/master/src/index.js#L83

serialize:

https://github.com/outline/rich-markdown-editor/blob/master/src/index.js#L113

For additional context you might look at the serializers written by the core team:
https://docs.slatejs.org/general/plugins#serializers

**Comment by markolofsen** [comment]
@tommoor merci beaucoup
