### ISSUE TITLE
Use marked as a dependency instead of paste code inside

### ISSUE THREAD

**Issue by Ognian** [tommoor/slate-md-serializer#26]
Hello
This is a great project. I have some questions suggestions wich I will post in separate issues..
I was going thru the code and noticed that the lexer of marked is used.
Why is the source pasted inside and not used as a dependency;  using marked as an external library would be better then inlining code. It would profit from fixes, addiction etc...
Thanks
Ognian

**Comment by tommoor** [comment]
The lexer has been heavily customized to support the needs of this project
