### ISSUE TITLE
Parsing without stripping markup

### ISSUE THREAD

**Issue by oskanberg** [tommoor/slate-md-serializer#32]
Is it possible to use this parser without stripping relevant markdown characters? i.e. \_this\_ becomes _\_this\__, instead of _this_.

**Comment by tommoor** [comment]
Afraid not, that’s not the way it’s designed to work. I think that would be quite tricky to implement but feel free to use this project as a base!

**Comment by oskanberg** [comment]
Okay, thanks for the speedy reply @tommoor.
