### ISSUE TITLE
Need help with use renderNode

### ISSUE THREAD

**Issue by Yevhenii-Prodan** [tommoor/slate-md-serializer#33]
I used serialize function to slate value, but tags from renderNode doesn't work, like headers, table, returned just empty.
`    onChange = ({ value }) => {
        const content = Markdown.serialize(value)
        this.setState({ value })
    }`
what I doing wrong?

**Comment by tommoor** [comment]
Impossible to tell from your code snippet I'm afraid, please see `rich-markdown-editor` for a full example of the use. This file in particular:

https://github.com/outline/rich-markdown-editor/blob/master/src/nodes.js

**Comment by Yevhenii-Prodan** [comment]
Thank's for answer, I've resolved that problem, your library work good.
